"""Added fifo_queue

Revision ID: 34dd41bd6298
Revises: e53939283138
Create Date: 2025-02-19 12:05:49.929091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34dd41bd6298'
down_revision: Union[str, None] = 'e53939283138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('fifo_queue', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tasks', sa.Column('queue_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'queue_date')
    op.drop_column('task_groups', 'fifo_queue')
    # ### end Alembic commands ###
