"""Assign executor

Revision ID: 35369e449604
Revises: 9475dc9c8153
Create Date: 2026-01-29 12:24:15.891256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35369e449604'
down_revision: Union[str, None] = '9475dc9c8153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('assign_executor', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_groups', 'assign_executor')
    # ### end Alembic commands ###
