"""add: ban_time

Revision ID: 47e7a34ff895
Revises: 809a0c3c301f
Create Date: 2024-08-27 11:26:46.931742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e7a34ff895'
down_revision: Union[str, None] = '809a0c3c301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('ban_minutes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('ban_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_time')
    op.drop_column('task_groups', 'ban_minutes')
    # ### end Alembic commands ###
