"""Added max_active_tasks

Revision ID: 491f031ec01b
Revises: 4eeda6936927
Create Date: 2025-01-13 12:10:21.945569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491f031ec01b'
down_revision: Union[str, None] = '4eeda6936927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('max_active_tasks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_groups', 'max_active_tasks')
    # ### end Alembic commands ###
