"""Added UserGroupRules

Revision ID: 4ab1330d862e
Revises: 34dd41bd6298
Create Date: 2025-02-21 09:34:53.649481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab1330d862e'
down_revision: Union[str, None] = '34dd41bd6298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_group_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('observer', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['task_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_group_roles')
    # ### end Alembic commands ###
