"""delete id from UserRole and testing_stage -> stage_type

Revision ID: 4eeda6936927
Revises: dbe94bc4415b
Create Date: 2024-11-25 16:08:03.295479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eeda6936927'
down_revision: Union[str, None] = 'dbe94bc4415b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('stage_type', sa.String(), nullable=True))
    op.drop_column('stages', 'test_stage')
    op.drop_column('users_roles', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_roles', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stages', sa.Column('test_stage', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('stages', 'stage_type')
    # ### end Alembic commands ###
