"""add: Stage.test_stage and Task.test_date

Revision ID: 5fceb61d0cac
Revises: cf1b4fe5c2fe
Create Date: 2024-07-23 15:39:19.842585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fceb61d0cac'
down_revision: Union[str, None] = 'cf1b4fe5c2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('test_stage', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('tasks', sa.Column('test_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'test_date')
    op.drop_column('stages', 'test_stage')
    # ### end Alembic commands ###
