"""add: auto_acceptance and unlimited_test

Revision ID: 62353849f4d7
Revises: bb5a8b6ee781
Create Date: 2024-10-23 10:30:48.449064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62353849f4d7'
down_revision: Union[str, None] = 'bb5a8b6ee781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('auto_acceptance', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('unlimited_test', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'unlimited_test')
    op.drop_column('task_groups', 'auto_acceptance')
    # ### end Alembic commands ###
