"""add: Role > access_all_stage

Revision ID: 632255f4718f
Revises: 6331fc97f6e4
Create Date: 2024-10-24 10:26:58.098654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632255f4718f'
down_revision: Union[str, None] = '6331fc97f6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('access_all_stage', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'access_all_stage')
    # ### end Alembic commands ###
