"""add: TaskGroup > analytics, notify

Revision ID: 6331fc97f6e4
Revises: 62353849f4d7
Create Date: 2024-10-24 09:34:22.841757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6331fc97f6e4'
down_revision: Union[str, None] = '62353849f4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('analytics', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('task_groups', sa.Column('notify', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_groups', 'notify')
    op.drop_column('task_groups', 'analytics')
    # ### end Alembic commands ###
