"""make region task group id unique

Revision ID: 7e15900c2a94
Revises: a22676a8d9b3
Create Date: 2026-01-23 19:55:46.796567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e15900c2a94'
down_revision: Union[str, None] = 'a22676a8d9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'regions', ['task_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regions', type_='unique')
    # ### end Alembic commands ###
