"""add: Task.allocated_time

Revision ID: 809a0c3c301f
Revises: 5fceb61d0cac
Create Date: 2024-07-25 09:26:54.470267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809a0c3c301f'
down_revision: Union[str, None] = '5fceb61d0cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('allocated_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'allocated_time')
    # ### end Alembic commands ###
