"""add regions to task

Revision ID: a22676a8d9b3
Revises: 480497c1bebc
Create Date: 2026-01-23 19:38:35.261968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22676a8d9b3'
down_revision: Union[str, None] = '480497c1bebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_group_id'], ['task_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'region_id')
    op.drop_table('regions')
    # ### end Alembic commands ###
