"""add: TaskGroup -> max_executor, close_from_test

Revision ID: b7691686dcee
Revises: 646fa50f5ef3
Create Date: 2024-11-02 17:38:06.314946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7691686dcee'
down_revision: Union[str, None] = '646fa50f5ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('max_executor_task', sa.Integer(), nullable=True))
    op.add_column('task_groups', sa.Column('close_from_test', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_groups', 'close_from_test')
    op.drop_column('task_groups', 'max_executor_task')
    # ### end Alembic commands ###
