"""add: Task.paid

Revision ID: bb5a8b6ee781
Revises: 47e7a34ff895
Create Date: 2024-09-03 14:29:06.255978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5a8b6ee781'
down_revision: Union[str, None] = '47e7a34ff895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('paid', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'paid')
    # ### end Alembic commands ###
