"""delete: admin access in users and stages; add: roles, role_access, max_in_stage

Revision ID: cf1b4fe5c2fe
Revises: 18ab48769196
Create Date: 2024-07-11 16:11:40.724349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1b4fe5c2fe'
down_revision: Union[str, None] = '18ab48769196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notify_queue', sa.Boolean(), nullable=False),
    sa.Column('change_any', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_access',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('insert', sa.Boolean(), nullable=False),
    sa.Column('extract', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('stages', sa.Column('max_tasks', sa.Integer(), nullable=True))
    op.add_column('stages', sa.Column('in_queue', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.drop_column('stages', 'admin_access')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key("users_role_id_fkey", 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'stages_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stages_admin', sa.BOOLEAN(), server_default=sa.false(), autoincrement=False, nullable=False))
    op.drop_constraint("users_role_id_fkey", 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('stages', sa.Column('admin_access', sa.BOOLEAN(), server_default=sa.false(), autoincrement=False, nullable=False))
    op.drop_column('stages', 'in_queue')
    op.drop_column('stages', 'max_tasks')
    op.drop_table('role_access')
    op.drop_table('roles')
    # ### end Alembic commands ###
