"""Added max_active_tasks for user

Revision ID: e53939283138
Revises: 491f031ec01b
Create Date: 2025-01-13 16:11:39.402608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53939283138'
down_revision: Union[str, None] = '491f031ec01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_active_tasks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_active_tasks')
    # ### end Alembic commands ###
