"""make region task group id unique

Revision ID: fc48face398c
Revises: 7e15900c2a94
Create Date: 2026-01-23 19:56:27.303010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc48face398c'
down_revision: Union[str, None] = '7e15900c2a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('regions_task_group_id_key', 'regions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('regions_task_group_id_key', 'regions', ['task_group_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
